[package]
name = "test1"
version = "0.1.0"
authors = ["王勤政 <qinzheng_wang@ziguangcn.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-crypto = "^0.2"
base64 = "0.12.3"
rand="0.3.0"